version: '3.8'


networks:
  traefik_net:
    external: true
  backend:

services:
  mongodb:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    # ports:
    #   - '27017:27017'
    volumes:
      - ./_data:/data/db
    networks:
      - traefik_net
      - backend

  mongo-express:
    image: mongo-express:latest
    ports:
      - '8083:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
    depends_on:
      - mongodb
    networks:
      - traefik_net
      - backend

  stopmotion_api:
    container_name: stopmotion_api
    build: ./server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"
    depends_on:
      - mongodb
    networks:
      - traefik_net
      - backend
    environment:
      MONGODB_SERVER: mongodb
      MONGODB_PORT: 27017
      MONGODB_ADMINUSERNAME: ${MONGO_USER}
      MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      MONGO_CONNECTION: ${MONGO_CONNECTION}
      PORT: 5000
    labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_net
        - traefik.http.routers.stopmotion_api.entrypoints=http
        - traefik.http.routers.stopmotion_api.rule=Host("stopmotion.sfzprojekt.de")
        - traefik.http.middlewares.stopmotion_api-https-redirect.redirectscheme.scheme=https
        - traefik.http.routers.stopmotion_api.middlewares=stopmotion_api-https-redirect
        - traefik.http.routers.stopmotion_api-secure.entrypoints=https
        - traefik.http.routers.stopmotion_api-secure.rule=Host("stopmotion.sfzprojekt.de")
        - traefik.http.routers.stopmotion_api-secure.tls=true
        - traefik.http.routers.stopmotion_api-secure.tls.certresolver=http
        - traefik.http.routers.stopmotion_api-secure.service=stopmotion_api
        - traefik.http.services.stopmotion_api.loadbalancer.server.port=5000